# Generated by Django 2.0.7 on 2018-08-31 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20180821_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adminroles',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_brief',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='0.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='userphoto',
            field=models.ImageField(default='0.jpg', upload_to=''),
        ),
    ]
