# Generated by Django 2.0.7 on 2018-07-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20180725_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
