# Generated by Django 2.0.7 on 2018-08-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_auto_20180801_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
