# Generated by Django 2.0.7 on 2018-08-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_auto_20180801_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
