# Generated by Django 2.0.7 on 2018-08-02 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_user_password1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password1',
        ),
    ]
